name: qote
description: A W.I.P. notes app.

publish_to: 'none' 

version: 0.1.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  http: ^0.13.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

flutter:
  uses-material-design: true
  assets:
      - assets/logo.png

flutter_icons:
  ios: true
  image_path: "assets/icon.png"
